# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\camunda_helper\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 679)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.ConfigBrowser = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigBrowser.sizePolicy().hasHeightForWidth())
        self.ConfigBrowser.setSizePolicy(sizePolicy)
        self.ConfigBrowser.setMinimumSize(QtCore.QSize(300, 0))
        self.ConfigBrowser.setObjectName("ConfigBrowser")
        self.ConfigsBrowser = QtWidgets.QVBoxLayout(self.ConfigBrowser)
        self.ConfigsBrowser.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ConfigsBrowser.setObjectName("ConfigsBrowser")
        self.loginLayout = QtWidgets.QHBoxLayout()
        self.loginLayout.setObjectName("loginLayout")
        self.loginLbl = QtWidgets.QLabel(self.ConfigBrowser)
        self.loginLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLbl.setObjectName("loginLbl")
        self.loginLayout.addWidget(self.loginLbl)
        self.loginBtn = QtWidgets.QPushButton(self.ConfigBrowser)
        self.loginBtn.setObjectName("loginBtn")
        self.loginLayout.addWidget(self.loginBtn)
        self.ConfigsBrowser.addLayout(self.loginLayout)
        self.configList = QtWidgets.QListWidget(self.ConfigBrowser)
        self.configList.setObjectName("configList")
        self.ConfigsBrowser.addWidget(self.configList)
        self.btnsLayout = QtWidgets.QHBoxLayout()
        self.btnsLayout.setObjectName("btnsLayout")
        self.addConfigBtn = QtWidgets.QPushButton(self.ConfigBrowser)
        self.addConfigBtn.setObjectName("addConfigBtn")
        self.btnsLayout.addWidget(self.addConfigBtn)
        self.removeConfigBtn = QtWidgets.QPushButton(self.ConfigBrowser)
        self.removeConfigBtn.setObjectName("removeConfigBtn")
        self.btnsLayout.addWidget(self.removeConfigBtn)
        self.ConfigsBrowser.addLayout(self.btnsLayout)
        self.gridLayout.addWidget(self.ConfigBrowser, 0, 0, 5, 1)
        self.configParamsContainer = QtWidgets.QWidget(self.centralwidget)
        self.configParamsContainer.setObjectName("configParamsContainer")
        self.configParamsContainer.setEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.configParamsContainer)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configContainerLayout = QtWidgets.QGridLayout()
        self.configContainerLayout.setObjectName("configContainerLayout")
        self.ConfigParams = QtWidgets.QGridLayout()
        self.ConfigParams.setObjectName("ConfigParams")
        self.configNameTbx = QtWidgets.QLineEdit(self.configParamsContainer)
        self.configNameTbx.setObjectName("configNameTbx")
        self.ConfigParams.addWidget(self.configNameTbx, 1, 1, 1, 1)
        self.hostTxb = QtWidgets.QLineEdit(self.configParamsContainer)
        self.hostTxb.setObjectName("hostTxb")
        self.ConfigParams.addWidget(self.hostTxb, 1, 3, 1, 1)
        self.configNameLbl = QtWidgets.QLabel(self.configParamsContainer)
        self.configNameLbl.setObjectName("configNameLbl")
        self.ConfigParams.addWidget(self.configNameLbl, 1, 0, 1, 1)
        self.hostLbl = QtWidgets.QLabel(self.configParamsContainer)
        self.hostLbl.setObjectName("hostLbl")
        self.ConfigParams.addWidget(self.hostLbl, 1, 2, 1, 1)
        self.instanceLbl = QtWidgets.QLabel(self.configParamsContainer)
        self.instanceLbl.setObjectName("instanceLbl")
        self.ConfigParams.addWidget(self.instanceLbl, 2, 0, 1, 1)
        self.instanceTxb = QtWidgets.QLineEdit(self.configParamsContainer)
        self.instanceTxb.setObjectName("instanceTxb")
        self.ConfigParams.addWidget(self.instanceTxb, 2, 1, 1, 3)
        self.configContainerLayout.addLayout(self.ConfigParams, 0, 0, 1, 1)
        self.taskTabs = QtWidgets.QTabWidget(self.configParamsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskTabs.sizePolicy().hasHeightForWidth())
        self.taskTabs.setSizePolicy(sizePolicy)
        self.taskTabs.setObjectName("taskTabs")
        self.move_task = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_task.sizePolicy().hasHeightForWidth())
        self.move_task.setSizePolicy(sizePolicy)
        self.move_task.setObjectName("move_task")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.move_task)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.closeTaskChbx = QtWidgets.QCheckBox(self.move_task)
        self.closeTaskChbx.setObjectName("closeTaskChbx")
        self.gridLayout_2.addWidget(self.closeTaskChbx, 0, 0, 1, 1)
        self.closeTaskTxb = QtWidgets.QLineEdit(self.move_task)
        self.closeTaskTxb.setObjectName("closeTaskTxb")
        self.gridLayout_2.addWidget(self.closeTaskTxb, 0, 1, 1, 1)
        self.startTaskChbx = QtWidgets.QCheckBox(self.move_task)
        self.startTaskChbx.setObjectName("startTaskChbx")
        self.gridLayout_2.addWidget(self.startTaskChbx, 1, 0, 1, 1)
        self.startTaskTxb = QtWidgets.QLineEdit(self.move_task)
        self.startTaskTxb.setObjectName("startTaskTxb")
        self.gridLayout_2.addWidget(self.startTaskTxb, 1, 1, 1, 1)
        # self.taskTabs.addTab(self.move_task, "")
        self.set_variables = QtWidgets.QWidget()
        self.set_variables.setObjectName("set_variables")
        # self.taskTabs.addTab(self.set_variables, "")
        self.update_version = QtWidgets.QWidget()
        self.update_version.setObjectName("update_version")
        # self.taskTabs.addTab(self.update_version, "")
        self.configContainerLayout.addWidget(self.taskTabs, 1, 0, 1, 1)
        self.ActionBtns = QtWidgets.QHBoxLayout()
        self.ActionBtns.setObjectName("ActionBtns")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ActionBtns.addItem(spacerItem)
        self.sendRequestBtn = QtWidgets.QPushButton(self.configParamsContainer)
        self.sendRequestBtn.setObjectName("sendRequestBtn")
        self.ActionBtns.addWidget(self.sendRequestBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ActionBtns.addItem(spacerItem1)
        self.configContainerLayout.addLayout(self.ActionBtns, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.configContainerLayout)
        self.gridLayout.addWidget(self.configParamsContainer, 1, 1, 1, 2)
        self.logPtx = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logPtx.sizePolicy().hasHeightForWidth())
        self.logPtx.setSizePolicy(sizePolicy)
        self.logPtx.setMinimumSize(QtCore.QSize(0, 0))
        self.logPtx.setReadOnly(True)
        self.logPtx.setObjectName("logPtx")
        self.gridLayout.addWidget(self.logPtx, 4, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.taskTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camunda request helper"))
        self.loginLbl.setText(_translate("MainWindow", "TextLabel"))
        self.loginBtn.setText(_translate("MainWindow", "Change"))
        self.addConfigBtn.setText(_translate("MainWindow", "Add"))
        self.removeConfigBtn.setText(_translate("MainWindow", "Remove"))
        self.configNameLbl.setText(_translate("MainWindow", "Name"))
        self.hostLbl.setText(_translate("MainWindow", "Host"))
        self.instanceLbl.setText(_translate("MainWindow", "Instance"))
        self.closeTaskChbx.setText(_translate("MainWindow", "Close"))
        self.startTaskChbx.setText(_translate("MainWindow", "Start"))
        # self.taskTabs.setTabText(self.taskTabs.indexOf(self.move_task), _translate("MainWindow", "Move task"))
        # self.taskTabs.setTabText(self.taskTabs.indexOf(self.set_variables), _translate("MainWindow", "Set variables"))
        # self.taskTabs.setTabText(self.taskTabs.indexOf(self.update_version), _translate("MainWindow", "Update version"))
        self.sendRequestBtn.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
